Quickstart-wordsmithing
jitsuin-inc/rkvst-docs pull request #11
Opened 2021-05-27 15:09 UTC by creator-of-data-assurance-hub

2021-05-27 15:36 UTC, leflambeur requested changes
L25 - I wasn't happy with what was already there but I'm also not sure that 'there's one key concept to shape your thinking' is the answer- we need a plainer/straightforward/less corporate way to say this I think - not sure what would make sense instead I'll think on it

L34 - 'in RKVST **it is** considered an Asset'

L36 - I think this should be restored as the reason it said `an identity, a description` is that it's an almost direct technical translation of the API (so makes the whole thing flow more into the technical concepts)

L60 - Instead of 'decisions about what should happen to it.' it should be'**or if there is a decision made about it**'

L77 - Both versions missed a 'what' in front of Asset

L107 - 'Events on Assets track that build a complete traceable historical record that builds trust in the key information needed by data users.' should be 'Events on Assets which builds a complete and traceable historical record; building trust in the information required by data consumers.

L111 - 'organisations' needs to be Americanized; I'm not sure we need the last sentence in L111

2021-05-27 18:32 UTC, JAG-UK requested changes

2021-05-27 18:32 UTC, JAG-UK commented on content/docs/quickstart/when-who-did-what-to-a-thing/index.md
> +Now we understand "Who did What to a Thing" we can bring it all together, creating a stream of untamperable, assured Events on Assets track that build a complete traceable historical record that buil
"track that build" ?

2021-05-28 08:59 UTC, creator-of-data-assurance-hub commented on content/docs/quickstart/when-who-did-what-to-a-thing/index.md
> +A Thing can be anything; a weather station sensor, an invoice or even a shipping container. Whatever this Thing may be, in RKVST considered it an ***Asset***.
fixed

2021-05-28 09:58 UTC, creator-of-data-assurance-hub commented on content/docs/quickstart/when-who-did-what-to-a-thing/index.md
> +Similar to an Asset, Events also have identities, descriptions and their own set of attributes. Importantly a key attribute of Events is tracking both ***when*** an action happens, ***what*** that ac
agree, fixed

2021-05-28 14:11 UTC, leflambeur approved these changes
LGTM

I'm roughly happy with this some minor changes are needed but I can pick those up in my next edit @JAG-UK I'll approve but feel to merge when you're happy

2021-05-28 15:31 UTC, merged